### PR TITLE
Refactor inputdata

### PR DESCRIPTION
**Pull request by TCatshoek**
This PR refactors the code that parses the input files for flexfringe. 

There are now separate classes for parsing csv and abbadingo formatted files, and their code has been made more independent of each other. This should fix the issue where certain csv files could not be parsed correctly because they contained characters that were used as delimiters in the abbadingo file format.

There are still some things to do before this can be merged, as streaming mode is currently broken and I am not sure what the best way to fix it is. Discussions with @RobBa underway :)

### CODE REVIEW

**Comment by TCatshoek** [comment]
TODO:
- Streaming mode inputdata
- Parsing trace and symbol attributes from abbadingo data

**Comment by TCatshoek** [comment]
I think this is good to go! Would be nice to get your feedback to see if I didn't miss anything.

**Comment by TCatshoek** [comment]
I found a fun (maybe) bug! 

Abbadingo traces defined as `1 0` don't get added to the list of traces collected by inputdata because they have no symbols. @SiccoVerwer, are these traces needed (I'm assuming yes, to mark the initial state as accepting or rejecting for example), and if so, how should we handle them?

**Comment by RobBa** [comment]
Yes, they’re needed for final probabilities (empty string)

**Comment by TCatshoek** [comment]
@RobBa does this solve your issue?

I'm still not 100% sure how to correctly assemble a trace with no symbols in it, so let me know if any weirdness related to that pops up

**Comment by TCatshoek** [comment]
Should be fixed now!

> @RobBa does this solve your issue?
> 
> I'm still not 100% sure how to correctly assemble a trace with no symbols in it, so let me know if any weirdness related to that pops up

**Comment by TCatshoek** [comment]
I wrote a quick script to compare the output of this branch to the previous inputdata code, it can be found [here](https://gist.github.com/TCatshoek/45cb9edd0ffb52d4f4babf0741e79fec#file-main-py)

It does not find any mismatches, flexfringe provides the exact same output with the refactored inputdata code for at least running alergia on all the staminadata files compared to the old code.

If @SiccoVerwer is ok with it, I think we can merge this finally

**Comment by TCatshoek** [comment]
Ok, predict seems to work now. I added a little convenience method to copy the alphabet mapping from the inputdata that gets loaded from the apta json, so we can easily create a new inputdata for the traces we want to predict that has the same mapping.

**Pull request merged**
